// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAI8-zfQ_SFjW7MJ6_7rMivxTrC9iUiRQ',
    appId: '1:493171238990:web:6ed50bc041d6565b37bb1f',
    messagingSenderId: '493171238990',
    projectId: 'weeing-front',
    authDomain: 'weeing-front.firebaseapp.com',
    storageBucket: 'weeing-front.firebasestorage.app',
    measurementId: 'G-P60V2K33QM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXGvFIrd8KqcwljRTCiaXSMbwrFD-6gk4',
    appId: '1:493171238990:android:13d6e71dca04c48a37bb1f',
    messagingSenderId: '493171238990',
    projectId: 'weeing-front',
    storageBucket: 'weeing-front.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnmbZx6QK6iFkuv4MSmCxg-5mp4fnJfa8',
    appId: '1:493171238990:ios:f8f5933f757ea69737bb1f',
    messagingSenderId: '493171238990',
    projectId: 'weeing-front',
    storageBucket: 'weeing-front.firebasestorage.app',
    iosBundleId: 'com.example.weeingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnmbZx6QK6iFkuv4MSmCxg-5mp4fnJfa8',
    appId: '1:493171238990:ios:f8f5933f757ea69737bb1f',
    messagingSenderId: '493171238990',
    projectId: 'weeing-front',
    storageBucket: 'weeing-front.firebasestorage.app',
    iosBundleId: 'com.example.weeingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAI8-zfQ_SFjW7MJ6_7rMivxTrC9iUiRQ',
    appId: '1:493171238990:web:53ca6edbecc4cb1737bb1f',
    messagingSenderId: '493171238990',
    projectId: 'weeing-front',
    authDomain: 'weeing-front.firebaseapp.com',
    storageBucket: 'weeing-front.firebasestorage.app',
    measurementId: 'G-BVFH15WPY1',
  );
}
